Updated usage example to add onAccessToken
kevin51jiang/react-spotify-auth pull request #57
Opened 2021-08-07 08:42 UTC by rpeyron

Hello,

Thanks for your useful component. Here is a very small PR to update usage example to add onAccessToken  and have a behavior more like one could expect just after have logged in without the need of refreshing the page (it took me some time to understand why, so it may help other users).

Hth,
Remi

2021-08-08 12:55 UTC, kevin51jiang requested changes
Hey, thanks for the PR!

There's just a few things I would like to change, since the example should be compatible with vanilla JS React, and it should still be able to store the auth token in a cookie in case the user decides to close + reopen the browser.

2021-08-08 12:55 UTC, kevin51jiang commented on README.md
> +  let [token, setToken] = useState('');
```suggestion
    const [token, setToken] = React.useState(Cookies.get("spotifyAuthToken"))
```

Just wanna keep it copy-pastable with vanilla React + ability to get token from storage

2021-08-08 12:55 UTC, kevin51jiang commented on README.md
> +          onAccessToken={(token:string) => { setToken(token)} }
```suggestion
          onAccessToken={(token) => setToken(token)}
```

No type annotation to keep it good with vanilla JS

2021-08-08 18:44 UTC, rpeyron commented
Hi, I have included the improvements you suggested. Thanks

2021-08-09 03:47 UTC, kevin51jiang commented
Thanks again :D

2021-08-09 03:48 UTC, merged